# Basic Information
title: Cheongun SEO
position: Undergraduate Student/Researcher @
position_link_text: MIPL
position_link: http://mipl.korea.ac.kr/
affiliation: School of Biomedical Engineering<br>Korea University<br>Seoul, South Korea
affiliation_link: https://www.korea.edu/
email: scw0922 (at) gmail.com<br>chung0922 (at) korea.ac.kr
url: https://seocheongun.github.io
baseurl: ""

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Cheongun SEO, Korea University, researcher, blog, portfolio
description: Cheongun SEO's personal homepage.
canonical: https://seocheongun.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
linkedin: https://www.linkedin.com/in/cheongun-seo-b60219393/
github_link: https://github.com/SeoCheongun
instagram: https://www.instagram.com/schnwn/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon-s.svg
favicon_dark: ./assets/img/favicon-s.svg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
